substitutions:
  name: l1
  device_description: "Monitor and control the Soyosource using the OEM WiFi dongle over RS485"
  external_components_source: github://syssi/esphome-soyosource-gtn-virtual-meter@main
  tx_pin_rs485: GPIO14
  rx_pin_rs485: GPIO5
  shelly_3em_url: "http://192.168.178.45/status/"

esphome:
  name: ${name}
  comment: ${device_description}
  project:
    name: "syssi.esphome-soyosource-gtn-virtual-meter"
    version: 2.2.0

esp8266:
  board: d1_mini

external_components:
  - source: ${external_components_source}
    refresh: 0s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Soyo1 Fallback Hotspot"
    password: "GaskrankeDP"

captive_portal:

web_server:
  local: true

ota:
  platform: esphome

logger:
  baud_rate: 0
  level: INFO

uart:
  - id: uart_0
    baud_rate: 9600
    tx_pin: GPIO1
    rx_pin: GPIO3
  - id: uart_1
    baud_rate: 4800
    tx_pin: ${tx_pin_rs485}
    rx_pin: ${rx_pin_rs485}

soyosource_modbus:
  - id: modbus0
    uart_id: uart_1
    # flow_control_pin: GPIO12

    # Optional settings
    #
    # The name is used as prefix for some log messages and should
    # help to distinguish between different instances/devices
    name: l1

soyosource_virtual_meter:
  - id: virtualmeter0
    soyosource_modbus_id: modbus0

    # The state of this sensor (instantaneous power in watt) is used as source
    power_id: powermeter0

    # Optional settings
    power_sensor_inactivity_timeout: 20s
    power_demand_calculation: NEGATIVE_MEASUREMENTS_REQUIRED
    min_power_demand: 0
    max_power_demand: 900
    zero_output_on_min_power_demand: true
    # Split/distribute the power demand if you have multiple inverters attached to the same RS485 bus
    power_demand_divider: 1
    # A positive buffer value (10) tries to avoid exporting power to the grid (demand - 10 watts)
    # A negative buffer value (-10) exports power to the grid (demand + 10 watts)
    buffer: 10
    # The operation_status_id sensor is expected here. Passing the operation_status won't work
    # The state is used to suspend the limiter if the operation status of the inverter isn't 0x0 (normal)
    operation_status_id: operation_status_id0

    # The update interval is important and defaults to 3 seconds. If the demand is sent too frequently
    # or rarely the interverter stops. TODO: Identify and validate the lower and upper update limit
    update_interval: 3s

soyosource_display:
  - id: display0
    uart_id: uart_0
    protocol_version: SOYOSOURCE_WIFI_VERSION
    update_interval: 5s

binary_sensor:
  - platform: soyosource_display
    fan_running:
      # 01 fan running
      name: "17 fan running"
    limiter_connected:
      # 02 limiter connected
      name: "18 limiter connected"

button:
  - platform: soyosource_display
    restart:
      # 03 restart
      name: "28 restart"

number:
  - platform: soyosource_virtual_meter
    soyosource_virtual_meter_id: virtualmeter0
    buffer:
      # 04 buffer
      name: "12 buffer"
      initial_value: 10
      restore_value: true
      mode: box
    manual_power_demand:
      # 05 manual power demand
      name: "21 manual power demand"
      max_value: 900
      mode: box
    max_power_demand:
      # 06 max power demand
      name: "14 max power demand"
      initial_value: 900
      max_value: 900
      restore_value: true
      mode: box
    power_demand_divider:
      # 07 power demand divider
      name: "27 power demand divider"
      initial_value: 1
      restore_value: true
      mode: box

  - platform: soyosource_display
    start_voltage:
      # 08 start voltage
      name: "31 start voltage"
    shutdown_voltage:
      # 09 shutdown voltage
      name: "29 shutdown voltage"
    # Maximum output power in limiter mode / Output power in constant power mode
    output_power_limit:
      # 10 output power limit
      name: "13 output power limit"
    start_delay:
      # 11 start delay
      name: "30 start delay"

select:
  - platform: soyosource_display
    operation_mode:
      # 12 operation mode
      name: "22 operation mode"
      optionsmap:
        1: "PV"
        2: "Battery Constant Power"
        17: "PV Limit"
        18: "Battery Limit"

sensor:
  - platform: soyosource_virtual_meter
    soyosource_virtual_meter_id: virtualmeter0
    power_demand:
      # 13 power demand
      name: "03 power demand"

  - platform: soyosource_display
    error_bitmask:
      # 14 error bitmask
      name: "16 error bitmask"
    operation_mode_id:
      # 15 operation mode id
      name: "24 operation mode id"
    operation_status_id:
      # 16 operation status id
      name: "26 operation status id"
      id: operation_status_id0
    battery_voltage:
      # 17 battery voltage
      name: "07 battery voltage"
    battery_current:
      # 18 battery current
      name: "06 battery current"
    battery_power:
      # 19 battery power
      name: "01 battery power"
    ac_voltage:
      # 20 ac voltage
      name: "11 AC voltage"
    ac_frequency:
      # 21 ac frequency
      name: "10 AC frequency"
    temperature:
      # 22 temperature
      name: "05 temperature"
    total_energy:
      # 23 total energy
      name: "09 total energy"
    output_power:
      # 24 output power
      name: "02 output power"

  - platform: template
    id: powermeter0
    # 25 Instantaneous Power
    name: "04 Instantaneous Power"
    unit_of_measurement: W
    device_class: "power"
    accuracy_decimals: 2
    update_interval: never

# tasmota & Shelly 3em
http_request:
  id: http_request0
  useragent: esphome/device
  timeout: 1000ms
  esp8266_disable_ssl_support: true

interval:
  - interval: 1100ms
    then:
      - http_request.get:
          url: ${shelly_3em_url}
          headers:
            Content-Type: application/json
          capture_response: true
          max_response_buffer_size: 2000
          on_response:
            then:
              - lambda: |-
                  json::parse_json(body, [](JsonObject root) -> bool {
                    id(powermeter0).publish_state(root["total_power"]);
                    return true;
                  });


switch:
  - platform: soyosource_virtual_meter
    soyosource_virtual_meter_id: virtualmeter0
    manual_mode:
      # 26 manual mode
      name: "20 manual mode"
      restore_mode: RESTORE_DEFAULT_OFF
    emergency_power_off:
      # 27 ermergency power off
      name: "15 emergency power off"
      restore_mode: RESTORE_DEFAULT_OFF

text_sensor:
  - platform: soyosource_virtual_meter
    soyosource_virtual_meter_id: virtualmeter0
    operation_mode:
      # 28 limiter operation mode
      name: "19 limiter operation mode"

  - platform: soyosource_display
    errors:
      # 29 errors
      name: "08 errors"
    operation_mode:
      # 30 operation mode
      name: "23 operation mode"
    operation_status:
      # 31 opertion status
      name: "25 operation status"
